version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: store_postgres
    restart: always
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: storeuser
      POSTGRES_PASSWORD: storepass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: store_api_dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://storeuser:storepass@postgres:5432/storedb
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    command: sh -c "./prisma/init.sh && npm run start:dev"

volumes:
  pgdata:
