services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - node:20-alpine
    ports:
      - "8080:8080"
    volumes:
      - /tmp/npm-cache:/root/.npm
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      MERCADO_PAGO_ACCESS_TOKEN: "${MERCADO_PAGO_ACCESS_TOKEN}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_USERNAME: "${REDIS_USERNAME}"
    depends_on:
      - db
      - redis
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_terax
    ports:
      - "19647:19647"
    networks:
      - app-network
    command: redis-server --save
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pg_data: {}